title: 可乐的小站
author_name: Cola.

tag1: 中二
tag2: 宅

github_url: https://github.com/Aizener

motto_prev: “花有重开日，人无再少年”
motto_last: “一个简单普通的男孩”

menu:
  - [小站首页, '/', 'icon-shouye']
  - [个人日志, '/log', 'icon-rizhi']
  - [友情链接, '/link', 'icon-youqinglianjie']
  - ['关于自己', '/about', 'icon-guanyuwomen']

links:
 - ['https://pic2.zhimg.com/80/v2-da2d9057695e5b3428d8d72a3cd65069_720w.jpg?source=1940ef5c', 'Sakura.', 'http://baidu.com']
 - ['https://pic2.zhimg.com/80/v2-da2d9057695e5b3428d8d72a3cd65069_720w.jpg?source=1940ef5c', 'Sakura.', 'http://baidu.com']
 - ['https://pic2.zhimg.com/80/v2-da2d9057695e5b3428d8d72a3cd65069_720w.jpg?source=1940ef5c', 'Sakura.', 'http://baidu.com']
 - ['https://pic2.zhimg.com/80/v2-da2d9057695e5b3428d8d72a3cd65069_720w.jpg?source=1940ef5c', 'Sakura.', 'http://baidu.com']
 - ['https://pic2.zhimg.com/80/v2-da2d9057695e5b3428d8d72a3cd65069_720w.jpg?source=1940ef5c', 'Sakura.', 'http://baidu.com']

notice: Hello~大噶好。唔系可乐爱宅着，欢迎你们来到我的博客小站，希望能在这里收获到有用的东西哦！

copyright: 浙公网安备 33010002000124号