author_name: Cola.

tag1: 中二
tag2: 宅

github_url: https://github.com/Aizener

motto_prev: “花有重开日，人无再少年”
motto_last: “一个简单普通的男孩”

notice: Hello~大噶好。唔系可乐爱宅着，欢迎你们来到我的博客小站，希望能在这里收获到有用的东西哦！

record: 浙公网安备 33010002000124号